

services:
  backend:
    build: .
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://cloudlab_user:a12345@cluster0.xzqvr0r.mongodb.net/cloud_lab?appName=Cluster0
      - PORT=5000
    networks:
      - mern-network

  frontend:
    build: ./client
    container_name: mern-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge